Add/home page/routing
frank12421/capstone-project pull request #15
Opened 2023-05-09 10:17 UTC by frank12421

2023-05-10 09:31 UTC, actyralf requested changes
Well done!
My main concern though is your `CreateCard` component that uses `if` blocks to render completely different content based on `type`, which makes it quite unflexible.
Additionally you might want to consider some naming convention proposals.

2023-05-10 09:31 UTC, actyralf commented on components/CreateCard.js
>    if (type === "plant") {
You are using `type` to decide wether to render a place or a plant. These two objects do not have a lot in common, you only want to apply the same styling to the container. 
This makes your card component very unflexible - if you want to use it with a 3rd type of content you would have to add another `if` block and so on. 
A better approach  would be to create a container component (e.g. `Card`) that simply renders children. When you instantiate this component (e.g. in `placelist.js` or `plantlist.js`), you can then use the appropriate content component as child.

2023-05-10 14:19 UTC, frank12421 commented
Hello Ralf, thanks for the good tips and your help. I have changed everything and made the code much clearer, I think. 
Please revise again. Thank you very much.

2023-05-11 02:43 UTC, frank12421 commented on components/Card.js
Hi Robin, thank you very much for your comments. I have changed this to Card on the advice of Ralf. Ralf had explained to me that styled components are actually normal components and can also be used in this way. https://github.com/frank12421/capstone-project/pull/15#discussion_r1189615820

2023-05-11 02:43 UTC, merged